### ISSUE TITLE
Platforms

### ISSUE THREAD

**Issue by divyenduz** [prisma/prisma2-e2e-tests#3]
# First

- [x] AWS Lambda #5 (@steebchen)
- [x] now via CLI (@divyenduz) https://github.com/prisma/prisma2-e2e-tests/pull/10
- [x] Heroku via CLI (@divyenduz) https://github.com/prisma/prisma2-e2e-tests/pull/4 (with `node_modules`, failing on https://github.com/prisma/photonjs/issues/390)
- [x] netlify via CLI (@divyenduz) https://github.com/prisma/prisma2-e2e-tests/pull/4
- [x] Serverless framework #20 (@steebchen)
- [x] CodeSandbox (@divyenduz) https://github.com/prisma/prisma2-e2e-tests/pull/25 (WIP exploration: https://github.com/prisma/prisma2-e2e-tests-csb)
- [x] Google Cloud Functions #22 (@steebchen)
- [x] Google Cloud Run (@steebchen)
- [x] Azure Functions Linux via #33 (@steebchen)
- [x] Firebase Functions via #68 (@steebchen)
- [x] Azure Functions Windows via #35 (blocked by https://github.com/prisma/prisma2/issues/1518) (@steebchen)
- [x] Netlify Plugins Beta (@divyenduz) https://github.com/prisma/prisma2-e2e-tests/pull/13 (Exploration: https://github.com/divyenduz/netlify-ci-build)
- (Netlify with ZISI_VERSION (@divyenduz) (WIP: https://github.com/prisma/prisma2-e2e-tests/pull/16, https://github.com/divyenduz/netlify-zishi))

# Next

- [x] ~~Docker~~ covered by https://github.com/prisma/binary-tester
- [x] ~now + next.js via CLI or GH integration https://github.com/prisma/prisma2/issues/1170~ It is fixed upstream. We don't need a separate test for this. 
- [x] Bundlers: webpack, parcel, rollup, snowpack via https://github.com/prisma/prisma2-e2e-tests/issues/31

# Next (maybe, if needed)

- now via GH integration
- netlify via GH integration
- ~~Up~~
- ~~Glitch~~

Reference: https://www.notion.so/prismaio/Important-Frameworks-Libraries-for-Prisma-3a95356a70f342f2ae999451bbd2d1fe#813eaba7398c4c7b9027fd79de913482

**Comment by steebchen** [comment]
Do we really want to differentiate between CLI and GH integrations? This might just make our testing more brittle with no actual additional value.

**Comment by divyenduz** [comment]
> Do we really want to differentiate between CLI and GH integrations? This might just make our testing more brittle with no actual additional value.

I kept it in the "next" list as a reminder to make a conscious decision of whether we need it or not. There might be differences in how bundling happens for example. 

I will do it manually first, and if there is a need, automate it. If there is no need, I will mark it as not required here.

**Comment by divyenduz** [comment]
> Do we really want to differentiate between CLI and GH integrations? This might just make our testing more brittle with no actual additional value.

Sadly, stuff breaks when deployment method is different https://github.com/divyenduz/netlify-ci-build 😞

**Comment by divyenduz** [comment]
@steebchen This issue can also be closed from my end.

**Comment by steebchen** [comment]
Can we tick `Netlify with ZISI_VERSION`? Otherwise, only Azure Functions is pending but is currently blocked by https://github.com/prisma/prisma2/issues/1518.

**Comment by divyenduz** [comment]
@steebchen we can close this without that, the other one is not in the list from DevRel, I found it out in my exploration and would track that separately.

**Comment by divyenduz** [comment]
Oops, just noted that Azure is blocked, re-opened. Feel free to close it.
