### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by steebchen** [prisma/prisma2-e2e-tests#38]
- [x] Express via #53 @steebchen 
- [x] Apollo Server via #99 @steebchen
- [ ] TypeGraphQL via #100 @steebchen
